eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://172.17.0.1:8761/eureka}
    
okta:
  oauth2:
    issuer: https://dev-88341131.okta.com/oauth2/default
    audience: api://default